openapi: 3.0.0
info:
  title: SendEmailAPI
  version: 1.0.0
  description: Tool to send password reset emails using OAuth 2.0 with client credentials.

servers:
  - url: https://api-dv.brightspeed.com/ccsutilservice/api/v1

paths:
  /sendEmail:
    post:
      summary: Send an email
      operationId: sendEmail
      security:
        - oauth2: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - from_email
                  - to_email
                  - subject
                  - body
                properties:
                  from_email:
                    type: string
                    example: ccs@brightspeed.com
                  to_email:
                    type: array
                    items:
                      type: string
                    example: ["user@example.com"]
                  subject:
                    type: string
                    example: Password Reset
                  body:
                    type: string
                    example: >
                      <img src='https://www.brightspeed.com/content/dam/brightspeed-brspd/images/logos/brightspeed-logo-full-color.svg' alt='Brightspeed Logo'><br><br>
                      Hello, please follow the instructions in this email to reset your password.
      responses:
        '200':
          description: Email sent successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Server error

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api-dv.brightspeed.com/oauth2/token
          scopes: {}